spring:
  datasource:
    url: jdbc:mysql://ec2-15-165-205-45.ap-northeast-2.compute.amazonaws.com:3306/test_db
    username: gagyeong
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
